name: Remove SnigelWeb Loader Scripts

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  clean_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove SnigelWeb Loader Scripts
      run: |
        # Remove script with `data-cfasync`
        find . -type f -not -path "./.github/*" -exec sed -i '/<script async data-cfasync="false" src="https:\/\/cdn.snigelweb.com\/adengine\/w3schools.com\/loader.js" type="text\/javascript"><\/script>/d' {} +

        # Remove script without `data-cfasync`
        find . -type f -not -path "./.github/*" -exec sed -i '/<script async src="https:\/\/cdn.snigelweb.com\/adengine\/w3schools.com\/loader.js" type="text\/javascript"><\/script>/d' {} +

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Remove SnigelWeb loader scripts" || echo "No changes to commit"

    - name: Push changes
      run: git push
