name: Remove Google Tag Manager

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  clean_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove Google Tag Manager snippets
      run: |
        find . -type f ! -path "./.github/*" -exec sed -i '/<!-- Google Tag Manager -->/,/<!-- End Google Tag Manager -->/d' {} +

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Remove Google Tag Manager snippets" || echo "No changes to commit"

    - name: Push changes
      run: git push
