name: Remove iframe snippet

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  clean_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove iframe snippet
      run: |
        find . -type f -exec sed -i '/<iframe src="../www.googletagmanager.com\/ns248c.html?id=GTM-KTCFC3S"/,+1d' {} \;

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Remove iframe snippet" || echo "No changes to commit"

    - name: Push changes
      run: git push
