name: Update SnigelWeb Loader Script

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_loader_url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update SnigelWeb Loader URLs
      run: |
        find . -type f -not -path "./.github/*" -exec sed -i 's|\.\./cdn\.snigelweb\.com/adengine/w3schools\.com/loader\.js|https://cdn.snigelweb.com/adengine/w3schools.com/loader.js|g' {} +

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update SnigelWeb loader URL" || echo "No changes to commit"

    - name: Push changes
      run: git push
